name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
  pull_request:
    branches:
      - main 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.7
          
      - name: Installing dependencies 
        run: go mod download
       
      - name: Test
        run: go test ./...
 
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Run golang lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.6

  build:
    name: Build & Upload Artifacts
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.7

      - name: Installing dependencies 
        run: go mod download

      - name: Build App 
        run: go build -o main    

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: main 
          
  docker:
    name: Docker Build , Security Scan & Push
    runs-on: ubuntu-latest
    needs: [test, lint]
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
    
      - name: Lowercase image name
        run:  echo "lower_image_name=${IMAGE_NAME,,}" >> $GITHUB_ENV
      
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
             
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: prod 
          push: false
          tags: | 
              ${{ env.REGISTRY }}/${{ env.lower_image_name }}:${{ github.run_id }}
              ${{ env.REGISTRY }}/${{ env.lower_image_name }}:latest
          load: true

      - name: Security Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.lower_image_name }}:${{ github.run_id }}'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          vuln-type: 'os,library'      
          
      - name: Push docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          target: prod
          tags: | 
              ${{ env.REGISTRY }}/${{ env.lower_image_name }}:${{ github.run_id }}
              ${{ env.REGISTRY }}/${{ env.lower_image_name }}:latest
      

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: [docker]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
    
      - name: Update tag in Helm chart
        uses: fjogeleit/yaml-update-action@v0.16.1
        with:
          valueFile: 'helm/go-web-app-chart/values.yaml'
          propertyPath: 'image.tag'         
          value: '${{github.run_id}}'
          masterBranchName: main
          targetBranch: main
          branch: ci/helm-update-${{github.run_id}}
          createPR: true
          message: 'ci: update Helm chart image tag to ${{github.run_id}}...'
      
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ fromJson(steps.update-helm.outputs.pull_request).number }}
          merge-method: squash
     